### ISSUE TITLE
SAMPVehicleCOLs.ccf release

### ISSUE THREAD

**Issue by Crayder** [codectile/cimulator#1]
The entire point of the ColAndreas Wizard that exports a database using the USER's files was to get around any issues with Rockstar that there could be (they personally consulted Rockstar about this btw). Releasing the object's info could go against legal terms and shit.

Now you just did the opposite by releasing the vehicle cols... xD

**Comment by codectile** [comment]
Extracting vehicle collision was not as straight as you think. At first I had to extract vehicle collision from the dff files using a tool and then creating a tool for myself to convert .col to .ccf. It's illegal to redistribute game assets (col, dff, img, etc...) and I am not doing that.

The main use of CA wizard was to reduce the work of updating the database along with SAMP updates.

**Comment by oscar-broman** [comment]
You're distributing derivative work, which is prohibited in the EULA.

I doubt anyone will take action, though, I just wanted to set the facts straight.
