### ISSUE TITLE
CR_IsActive Crashes the server...

### ISSUE THREAD

**Issue by Crayder** [codectile/cimulator#1]

**Comment by codectile** [comment]
No code? By the way I tested the test gamemode and it worked pretty well for me.

**Comment by codectile** [comment]
I am pretty sure that you are calling `CR_IsActive` before creating a collision volume or after deleting it.

**Comment by Crayder** [comment]
Actually I'm calling it just after creating it and it crashes.

**Comment by codectile** [comment]
Frankly speaking, I need the code to understand.

**Comment by Crayder** [comment]
I had to rewrite the code to reproduce it. I wasn't home when I ran it before (which is why I couldn't test it IG as I said before). I don't want to boot into Win7 just to use it so could you add WinXP dependencies? If not I won't be using the Cimulator for a while. Not sure which dependencies are needed as you didn't actually release the source. All I know so far is that is requires GetTickCount64.

**Comment by codectile** [comment]
"cimulator" does not use `GetTickCount` function as of now. To let you know, I have tested `CR_IsActive` by calling it just after creating a collision volume and the result was without any errors. Just try on WinXP it might work.

**Comment by Crayder** [comment]
I have tried to use it on XP, as I just said before. It won't run because it requires GetTickCount64.
![image](https://cloud.githubusercontent.com/assets/9919010/10115618/6fb194aa-63dc-11e5-8c81-88a83f7d6c48.png)

**Comment by codectile** [comment]
For the first time, I have compiled something for WinXP. Please re-download the file.

**Comment by Crayder** [comment]
Still the same problem, and yes I got the plugin from the forXP folder.

**Comment by codectile** [comment]
I am uploading a new one. I'll adit this comment as soon as it gets uploaded.

**Comment by Crayder** [comment]
All seems well now.

CA_IsActive did happen to crash the server again. I just compiled in debug mode and realized what I did wrong (I was in fact calling it just before I created it, and directly after). Perhaps you should add an internal check to prevent the crashes?

**Comment by codectile** [comment]
I will try to add an internal check to prevent crashes. So, is it simulating well now?

**Comment by Crayder** [comment]
Actually I'm not sure. I used code very similar to your example script but the objects are only streaming in when the object is done simulating...

**Comment by codectile** [comment]
use `Streamer_Update(playerid)` as soon as you spawn an object.

**Comment by Crayder** [comment]
Yea I figured that out...

The simulation isn't as good as I hoped yet. It is really slow even though I have it set for 20 millisecond intervals. Just a few objects uses a lot of CPU (which isn't a good CPU btw, so not too surprising). A lot of objects don't go where they should, some go crazy during the simulation with random rotations and falling through other objects.

It is pretty badass though.

**Comment by codectile** [comment]
For only a server side simulation its good(according to me). To make the simulation extremely smooth I need to hack into GTA SanAndreas and for a proper simulation we must simulate object, both client and server side. Approx 48000 objects isn't few. I think improper collision shapes causes weird rotation or it can be my fault as well and what do you mean by `falling through other objects`?

**Comment by codectile** [comment]
Solved the issue. Now, `CR_IsActive(index)` does not cause any crashes when it is called before creating a collision volume.
