### ISSUE TITLE
Dead stop, no revival?

### ISSUE THREAD

**Issue by Crayder** [codectile/cimulator#2]
Once an object is at it's stopping point it is impossible to move again (via `CR_SetLinearVelocity`). Is it meant to be like that?

**Comment by codectile** [comment]
No, not actually. I will add function for sleeping thresholds. I like when objects get deactivated to reduce the stress on CPU during the simulation. Though, you can activate it as well. I will add a function soon.

**Comment by Crayder** [comment]
Also, is there a way to add static world objects? Like, objects that will not move but will interact with moving objects?

I haven't been able to physically test it in game, I just have a script that prints the transforms and such.

**Comment by codectile** [comment]
Of course, you can create static objects. The whole map is a chunk of static rigid bodies. To add a static object the set the mass to zero.

**Comment by codectile** [comment]
I have implemented, `CR_Activate(index)`. Please re-download the file.

Example:
```c++
if(!CR_IsActive(index))
{
    CR_Activate(index);
    CR_SetLinearVelocity(index, x, y, z);
}
```

**Comment by Crayder** [comment]
Sweet, I'll test it out later.

**Comment by codectile** [comment]
By the way try to avoid restitution, it causes improper simulations and collision detection does not work well. It might be a problem of bullet.
