### ISSUE TITLE
CR_Init...?

### ISSUE THREAD

**Issue by Crayder** [codectile/cimulator#3]
Like ColAndreas, this plugin should have a function to use to load the SA map. If the function isn't used at all the SA map will not be loaded.

**Comment by codectile** [comment]
cimulator is not ColAndreas.
To initialize map, use `CR_Load(Float:worldrest = 1.0)` there is an option float parameter for world restitution/bounciness.
To just simple initialize the map, `CR_Load()` under gamemodeinit().
With world restitution, `CR_Load(5.0)`, you can pass any floating point argument as the coefficient of restitution.

**Comment by Crayder** [comment]
So, if I do not use CR_Load, the SA map will not be loaded? Good, closing.

**Comment by codectile** [comment]
No, it map will not be loaded if you do not use CR_Load.
