### ISSUE TITLE
Per Player Collision Approximation

### ISSUE THREAD

**Issue by codectile** [codectile/cimulator#4]
Trying to implement per player collision approximations.

Benefits:

* player collision detection. (accuracy up to 85%)
* interaction between collision volumes and players.
and much more...

**Comment by Crayder** [comment]
Will this be more stressful?

**Comment by codectile** [comment]
No not at all if your aim is to only detect collisions like ray tracing. But if you simulate objects as well as players then there might be a little stress added. I'll limit the amount of players to 30.

**Comment by Crayder** [comment]
The only reason I'd use this is for simulating, and I'd require more than 30 players. Could it be toggle-able? You could also make it read the max_players in server.cfg.

**Comment by codectile** [comment]
How much players you want to be simulated?

**Comment by Crayder** [comment]
Let's say one server has 40-60 avg, and the other always has above 100 avg. There limits should be adjusted accordingly.

**Comment by codectile** [comment]
Okay so I decided not to limit the player count for now. I just encountered the playing football ingame would be too much fun. Though there are some bugs that needs to be resolved.

**Comment by Crayder** [comment]
Remember not to rush, you literally have all the time you need.

**Comment by codectile** [comment]
I literally have to rush, I will completely be inactive from December till March.

**Comment by codectile** [comment]
By the way I am quiet eager to know how you are going to simulate objects plus players on your single core?

**Comment by Crayder** [comment]
That's impossible... XD
As I said before, the servers that I'm using as example aren't mine. Even if they were I wouldn't be running them on this piece of shit. I'd definitely have a good VPS, and I may soon.

**Comment by codectile** [comment]
Make sure you have a really good server. Maybe i'll update the release tomorrow with player collision functionality.

**Comment by Crayder** [comment]
Q: How exactly are you using player models? Are you using the actually skin model or like a cylinder in the player's place?

**Comment by codectile** [comment]
I am using simple collision shape approximations. It could he a capsule, cylinder, or a box. Honestly, I am using capsule because it looks kinda more accurate. As it is an  old game without any ragdoll physics, I had no other choice even gta itself uses simple shapes.

**Comment by Crayder** [comment]
That's what I expected, good idea.

**Comment by codectile** [comment]
By the way,  would you like to have a functionality by which you can choose your own collision shape with your own own data(such as radius, height, min, max...)?

**Comment by Crayder** [comment]
For players?

**Comment by codectile** [comment]
yes.

**Comment by Crayder** [comment]
I guess it wouldn't be too bad.

**Comment by codectile** [comment]
player approximations implemented. I will try to add a demo on player collisions.
