### ISSUE TITLE
[Enhance] "contactTest" simulation.

### ISSUE THREAD

**Issue by Crayder** [codectile/cimulator#5]
Add a function that would return true if and only if a model, at a specified transform (pos and rot), collides with any other object in the world.

`CR_ContactTest(model, x, y, z, rx, ry, rz);`

**Comment by codectile** [comment]
I can try implementing it, but it will only be for dynamic objects.

**Comment by Crayder** [comment]
By dynamic you mean... what?

The model parameter in my example function would not be an actual object ID, it's just a model to test. It would see if that particular model in that particle place would collide with any objects that are included in the cimulator's current map. That map being all of the GTASA map and the "cimulated" objects.

**Comment by codectile** [comment]
So you mean, you want to forecast collision at a particular place?

**Comment by Crayder** [comment]
Forecast? I don't think so. The model won't really be created in that position. It will just be tested there.

I'm trying to think of a good example.

Ok, say I had a hand mapped forest in the streets of Los Santos for some odd reason. Now, I want to take a cow and put it on the street somewhere. A ray cast down would determine the position height. If CR_ContactTest for the cow model in the position and some random rotation returned false that would be deemed an invalid position.

**Comment by codectile** [comment]
Oh I get what you mean, I guess.
So you want to check if the world objects overlapping with the cow object, right?

**Comment by Crayder** [comment]
Yes, basically.

**Comment by codectile** [comment]
Then the function would look like this: `CR_ContactTest(objectid, x, y, z, rx, ry, rz);`

```c++
if(!strcmp("/command", cmdtext, true, 8))
{
    if(CR_ContactTest(objectid, x, y, z, rx, ry, rz))
        DestroyDynamicObject(objectid);
}
```

**Comment by Crayder** [comment]
No, I don't want to physically create the object in the server. I only want it to be tested. Like;

```Pawn
	//Loop through a bunch of points.
	for(new Float:X; X < 100.0; X++) for(new Float:Y; Y < 100.0; Y++) {
		//Large based tree.
		if(!CR_ContactTest(664, X, Y, 3.0, 0.0, 0.0, 0.0)) {
			//Create it here because the model doesn't collide with the world.
			CreateDynamicObject(664, X, Y, 3.0, 0.0, 0.0, 0.0);
		}
	}
```

**Comment by codectile** [comment]
I guess this function will be good for mapping.

**Comment by Crayder** [comment]
Yes. Another great example would be vehicle models. When they are implemented into the cadb, that is.

CMD:car(playerid, params[])
{
	new model;
	sscanf(params, "k<vehicle>", model); //'vehicle' being a kustom sscanf parameter I made.
	if(model == -1)
		//return send invalid model message
		
	//calculate vehicle's desirable position and rotation using player position, model sizes, and a ray cast down.
	if(CR_ContactTest(model, X, Y, Z, 0.0, 0.0, R))
		//return send invalid position message
	
	//create vehicle because the position was valid
	return 1;
}

**Comment by codectile** [comment]
contactTest drove me crazy. Though, it needs some testing.

**Comment by Crayder** [comment]
Yea I tried to play with it before but it never did what I expected.

**Comment by codectile** [comment]
contactTest is fully functional with and without simulation. A lot more to do, raytrace function which returns modelid, source cleanup, and.... do you have any other suggestions?

**Comment by Crayder** [comment]
If you were to return a modelid, you would need to return all modelids. An object wouldn't always only collide with one other object.

**Comment by codectile** [comment]
I said, a "raytrace" function which returns modelid.

**Comment by Crayder** [comment]
Ahh, yea

**Comment by codectile** [comment]
contactTest is now implmented.

**Comment by Crayder** [comment]
So the object must be created to use CR_ContactTest?

That's not how I needed it to be. Like, it should've been how I described above so we can test it before actually creating the object.

**Comment by codectile** [comment]
It is not necessary to create ingame object for contact tests.

For mapping purpose:
```
Create a static collision volume
Test it (contact test)
If no collision detected
    create object in the position of the collision volume
```

Basically, creation of objects ingame and creation collision volumes are not hooked up internally.

**Comment by Crayder** [comment]
I know they are not linked, but you could easily create the volume in the cimulator's source instead of the scripters having to create one themselves since it is basically temporary.

**Comment by codectile** [comment]
I can't, because every time a collision object will be created on the call of `CR_ContactTest` and it will use more memory and the major drawback would be we cannot flush that memory manually. I guess, you have referred the contact test code in another issue.

**Comment by Crayder** [comment]
Fair enough.

**Comment by codectile** [comment]
I guess, I have resolved an issue where deleting memory during simulation caused crashing of the server. So, yes I can try to implement a function based on your need.

**Comment by codectile** [comment]
`CR_ContactTestEx` has been implemented.
